export default function Sidebar() {
  return (
    <aside className="w-64 shrink-0 hidden md:flex self-start">
      <div className="flex flex-col self-start rounded-2xl border border-gray-200 bg-white w-full sticky top-6">
        {/* Brand */}
        <div className="flex items-center gap-3 mb-2 p-6 pl- border-b">
          <div className="w-8 h-8 rounded-lg bg-black text-white flex items-center justify-center text-sm font-bold">Z</div>
          <div className="text-xl font-medium tracking-tight text-gray-900">ZODIAC OS</div>
        </div>

        {/* Navigation Bar (Icons were generated by Cursor for the simplicity of the project) */}
        <nav className="space-y-1 p-2">
          {[
            { label: "Home", icon: (
              <path d="M3 11.5L12 4l9 7.5V20a2 2 0 01-2 2h-4v-6H9v6H5a2 2 0 01-2-2v-8.5z" />
            )},
            { label: "Accounts", icon: (
              <path d="M12 12a4 4 0 100-8 4 4 0 000 8zm7 10v-1a6 6 0 00-12 0v1" />
            )},
            { label: "Roles", icon: (
              <path d="M4 7h16M4 12h16M4 17h10" />
            )},
            { label: "Transactions", icon: (
              <path d="M4 7h6v6H4zM14 11h6v6h-6zM4 17h6v2H4zM14 7h6v2h-6z" />
            )},
            { label: "Swap", icon: (
              <path d="M7 7h10M7 7l2-2M7 7l2 2M17 17H7m10 0l-2-2m2 2l-2 2" />
            )},
            { label: "Stake", icon: (
              <path d="M12 3v18m-7-5h14M6 10h12" />
            )},
            { label: "Bridge", icon: (
              <path d="M3 17h18M5 17a7 7 0 0114 0" />
            )},
            { label: "Settings", icon: (
              <path d="M12 8a4 4 0 100 8 4 4 0 000-8zm8 4a2 2 0 01-1.73 1.98 7.97 7.97 0 01-.87 2.1l1.23 1.23-1.42 1.42-1.23-1.23a7.97 7.97 0 01-2.1.87A2 2 0 0112 22a2 2 0 01-1.98-1.73 7.97 7.97 0 01-2.1-.87l-1.23 1.23-1.42-1.42 1.23-1.23a7.97 7.97 0 01-.87-2.1A2 2 0 014 12c0-.1 0-.2.02-.3a7.97 7.97 0 01.87-2.1L3.66 8.37l1.42-1.42 1.23 1.23c.65-.38 1.36-.68 2.1-.87A2 2 0 0112 4c.1 0 .2 0 .3.02.74.19 1.45.49 2.1.87l1.23-1.23 1.42 1.42-1.23 1.23c.38.65.68 1.36.87 2.1.01.1.01.2.01.3z" />
            )},
          ].map((item) => (
            <a
              key={item.label}
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm text-gray-500 hover:bg-gray-100 group cursor-pointer transition-colors duration-150"
              style={{ transitionTimingFunction: 'ease' }}
            >
              <svg
                className="w-5 h-5 text-gray-500 group-hover:text-gray-900 transition-colors duration-150"
                style={{ transitionTimingFunction: 'ease' }}
                viewBox="0 0 24 24"
                fill="currentColor"
                stroke="currentColor"
                strokeWidth="1.8"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                {item.icon}
              </svg>
              <span className="text-md font-medium text-gray-900">{item.label}</span>
            </a>
          ))}
        </nav>

        {/* Profile */}
        <div className="mt-48 flex items-center justify-between border-t p-3">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-gray-300 overflow-hidden" />
            <div>
              <div className="text-sm font-medium text-gray-900">Erica</div>
              <div className="text-xs text-gray-500">erica@example.com</div>
            </div>
          </div>
          <svg className="w-4 h-4 text-gray-700" viewBox="0 0 24 24" fill="none" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M19 15l-7-7-7 7" />
          </svg>
        </div>
      </div>
    </aside>
  );
}


